"use client";

import { FormEvent, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { PencilSimple, Plus, Ticket, Trash } from "@phosphor-icons/react";
import { adminService } from "@/services/admin.service";
import { Coupon, CouponRequestData } from "@/types";
import { queryKeys } from "@/lib/query-keys";
import { formatCurrency, formatDate } from "@/utils/format";
import { useUIStore } from "@/stores/useUIStore";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { StatusBadge } from "@/components/ui/status-badge";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/feedback-state";

const nowLocal = () => new Date().toISOString().slice(0, 16);
const emptyCoupon = (): CouponRequestData => ({ code: "", title: "", discountType: "PERCENTAGE", discountValue: 0, minOrderAmount: 0, maxDiscountAmount: undefined, startDate: nowLocal(), endDate: nowLocal(), usageLimit: 100, usagePerUser: 1, isActive: true });
export default function AdminCouponsPage() {
  const client = useQueryClient(); const { addToast } = useUIStore(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Coupon | null>(null); const [values, setValues] = useState<CouponRequestData>(emptyCoupon); const [errors, setErrors] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  const query = useQuery({ queryKey: queryKeys.adminCoupons, queryFn: () => adminService.getAdminCoupons() });
  function show(coupon?: Coupon) { setEditing(coupon || null); setValues(coupon ? { code: coupon.code, title: coupon.title, discountType: coupon.discountType, discountValue: coupon.discountValue, minOrderAmount: coupon.minOrderAmount, maxDiscountAmount: coupon.maxDiscountAmount, startDate: coupon.startDate.slice(0, 16), endDate: coupon.endDate.slice(0, 16), usageLimit: coupon.usageLimit, usagePerUser: coupon.usagePerUser, isActive: coupon.isActive } : emptyCoupon()); setErrors({}); setOpen(true); }
  function update<K extends keyof CouponRequestData>(field: K, value: CouponRequestData[K]) { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); }
  async function save(event: FormEvent) { event.preventDefault(); const next: Record<string, string> = {}; if (!values.code.trim()) next.code = "Vui lòng nhập mã"; if (!values.title.trim()) next.title = "Vui lòng nhập tên chương trình"; if (values.discountValue <= 0) next.discountValue = "Giá trị cần lớn hơn 0"; if (!values.startDate) next.startDate = "Vui lòng chọn ngày bắt đầu"; if (!values.endDate || values.endDate <= values.startDate) next.endDate = "Ngày kết thúc cần sau ngày bắt đầu"; setErrors(next); if (Object.keys(next).length) return; setSaving(true); try { const response = editing ? await adminService.updateCoupon(editing.id, values) : await adminService.createCoupon(values); if (!response.success) { setErrors(response.errors || {}); throw new Error(response.message); } await client.invalidateQueries({ queryKey: queryKeys.adminCoupons }); setOpen(false); addToast("success", editing ? "Mã ưu đãi đã cập nhật." : "Mã ưu đãi đã được tạo."); } catch { addToast("error", "Chưa thể lưu mã ưu đãi."); } finally { setSaving(false); } }
  async function remove(id: number) { try { await adminService.deleteCoupon(id); await client.invalidateQueries({ queryKey: queryKeys.adminCoupons }); addToast("success", "Mã ưu đãi đã được xóa."); } catch { addToast("error", "Chưa thể xóa mã ưu đãi."); } }
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-extrabold tracking-[-0.02em]">Mã ưu đãi</h1><p className="mt-2 text-sm text-muted">Tạo và theo dõi chương trình giảm giá.</p></div><Button className="gap-2" onClick={() => show()}><Plus /> Tạo mã</Button></header>{query.isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Skeleton className="h-64" /><Skeleton className="h-64" /></div> : query.isError ? <ErrorState onRetry={() => query.refetch()} /> : !query.data?.data?.length ? <EmptyState title="Chưa có mã ưu đãi" description="Tạo mã đầu tiên khi cửa hàng có chương trình phù hợp." /> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{query.data.data.map((coupon) => <article key={coupon.id} className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-start justify-between gap-4"><span className="grid h-11 w-11 place-items-center rounded-[10px] bg-accent-soft text-accent"><Ticket /></span><StatusBadge status={coupon.isActive ? "ACTIVE" : "INACTIVE"} /></div><p className="mt-6 font-mono text-lg font-extrabold text-accent">{coupon.code}</p><h2 className="mt-2 text-sm font-bold">{coupon.title}</h2><p className="mt-3 text-sm text-muted">Giảm <strong className="text-ink">{coupon.discountType === "PERCENTAGE" ? `${coupon.discountValue}%` : formatCurrency(coupon.discountValue)}</strong></p><div className="mt-5 border-t border-line pt-4 text-xs leading-5 text-muted"><p>Đã dùng {coupon.usedCount} / {coupon.usageLimit}</p><p>Kết thúc {formatDate(coupon.endDate)}</p></div><div className="mt-4 flex justify-end"><Button variant="ghost" size="sm" onClick={() => show(coupon)}><PencilSimple /> Sửa</Button><ConfirmDialog trigger={<Button variant="ghost" size="sm" className="text-danger"><Trash /> Xóa</Button>} title="Xóa mã ưu đãi?" description="Mã này sẽ không còn áp dụng được cho đơn mới." confirmLabel="Xóa" destructive onConfirm={() => remove(coupon.id)} /></div></article>)}</section>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing ? "Sửa mã ưu đãi" : "Tạo mã ưu đãi"}><form onSubmit={save} noValidate className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input label="Mã" value={values.code} error={errors.code} onChange={(event) => update("code", event.target.value.toUpperCase())} /><Input label="Tên chương trình" value={values.title} error={errors.title} onChange={(event) => update("title", event.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><Select label="Loại giảm" value={values.discountType} onChange={(event) => update("discountType", event.target.value as CouponRequestData["discountType"])}><option value="PERCENTAGE">Phần trăm</option><option value="FIXED_AMOUNT">Số tiền</option></Select><Input label="Giá trị giảm" type="number" min="0" value={values.discountValue} error={errors.discountValue} onChange={(event) => update("discountValue", Number(event.target.value))} /></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Đơn tối thiểu" type="number" min="0" value={values.minOrderAmount} onChange={(event) => update("minOrderAmount", Number(event.target.value))} /><Input label="Giảm tối đa" type="number" min="0" value={values.maxDiscountAmount ?? ""} onChange={(event) => update("maxDiscountAmount", event.target.value ? Number(event.target.value) : undefined)} /></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Bắt đầu" type="datetime-local" value={values.startDate} error={errors.startDate} onChange={(event) => update("startDate", event.target.value)} /><Input label="Kết thúc" type="datetime-local" value={values.endDate} error={errors.endDate} onChange={(event) => update("endDate", event.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><Input label="Giới hạn lượt dùng" type="number" min="1" value={values.usageLimit} onChange={(event) => update("usageLimit", Number(event.target.value))} /><Input label="Lượt dùng mỗi khách" type="number" min="1" value={values.usagePerUser} onChange={(event) => update("usagePerUser", Number(event.target.value))} /></div><label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" checked={values.isActive} onChange={(event) => update("isActive", event.target.checked)} className="h-4 w-4 accent-accent" /> Đang hoạt động</label><div className="flex justify-end"><Button type="submit" isLoading={saving}>{editing ? "Lưu thay đổi" : "Tạo mã"}</Button></div></form></DialogContent></Dialog>
  </div>;
}
